"""Agrega tabla de ordenes

Revision ID: 58242a57313f
Revises: 181bb5797cd8
Create Date: 2018-04-08 15:31:16.399521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58242a57313f'
down_revision = '181bb5797cd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_product',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_product')
    op.drop_table('order')
    # ### end Alembic commands ###
