"""Agrega cantidad a la tabla iterpuesta

Revision ID: ca6718772e81
Revises: 58242a57313f
Create Date: 2018-04-08 15:35:10.942618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca6718772e81'
down_revision = '58242a57313f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_product', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_product', 'quantity')
    # ### end Alembic commands ###
